const lawyersData = [
  {
    name: 'Ankit Sharma',
    specialization: 'Criminal Defense',
    experience: '8 years',
    rating: 4.4,
    email: 'ankit.sharma@example.com',
    phone: '555-987-6543',
    location: 'Jaipur, Rajasthan',
    firm: 'Sharma Criminal Defense',
    education: 'National Law University, Delhi',
    practicingAreas: ['Criminal Defense', 'Assault', 'Homicide'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Ravi Kumar',
    specialization: 'Property Law',
    experience: '12 years',
    rating: 4.6,
    email: 'ravi.kumar@example.com',
    phone: '555-876-5432',
    location: 'Mumbai, Maharashtra',
    firm: 'Kumar & Co.',
    education: 'University of Mumbai',
    practicingAreas: ['Property Law', 'Real Estate Disputes', 'Land Transactions'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Priya Verma',
    specialization: 'Family Law',
    experience: '5 years',
    rating: 4.3,
    email: 'priya.verma@example.com',
    phone: '555-765-4321',
    location: 'Gurugram, Haryana',
    firm: 'Verma Family Law',
    education: 'Banaras Hindu University',
    practicingAreas: ['Divorce', 'Child Custody', 'Alimony'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Vikram Patel',
    specialization: 'Corporate Law',
    experience: '15 years',
    rating: 4.7,
    email: 'vikram.patel@example.com',
    phone: '555-654-3210',
    location: 'Ahmedabad, Gujarat',
    firm: 'Patel Corporate Advisors',
    education: 'Indian Institute of Management, Ahmedabad',
    practicingAreas: ['Corporate Law', 'Mergers & Acquisitions', 'Commercial Contracts'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Neha Gupta',
    specialization: 'Tax Law',
    experience: '9 years',
    rating: 4.8,
    email: 'neha.gupta@example.com',
    phone: '555-543-2109',
    location: 'Bengaluru, Karnataka',
    firm: 'Gupta Tax Consultants',
    education: 'National Institute of Taxation',
    practicingAreas: ['Tax Law', 'Income Tax', 'Corporate Taxation'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Amit Mehta',
    specialization: 'Intellectual Property Law',
    experience: '7 years',
    rating: 4.6,
    email: 'amit.mehta@example.com',
    phone: '555-432-1098',
    location: 'Chandigarh, Chandigarh',
    firm: 'Mehta IP Law',
    education: 'Punjab University, Chandigarh',
    practicingAreas: ['Copyright Law', 'Patent Law', 'Trademark Law'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Sanya Kapoor',
    specialization: 'Immigration Law',
    experience: '4 years',
    rating: 4.5,
    email: 'sanya.kapoor@example.com',
    phone: '555-321-0987',
    location: 'Delhi, Delhi',
    firm: 'Kapoor Immigration Law',
    education: 'Jindal Global Law School',
    practicingAreas: ['Immigration', 'Visas', 'Green Cards'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Kunal Joshi',
    specialization: 'Environmental Law',
    experience: '11 years',
    rating: 4.9,
    email: 'kunal.joshi@example.com',
    phone: '555-210-9876',
    location: 'Pune, Maharashtra',
    firm: 'Joshi Environmental Law',
    education: 'Symbiosis Law School',
    practicingAreas: ['Environmental Regulations', 'Pollution Laws', 'Wildlife Conservation'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Sneha Reddy',
    specialization: 'Labor Law',
    experience: '6 years',
    rating: 4.4,
    email: 'sneha.reddy@example.com',
    phone: '555-109-8765',
    location: 'Hyderabad, Telangana',
    firm: 'Reddy & Co.',
    education: 'Osmania University',
    practicingAreas: ['Labor Law', 'Workplace Disputes', 'Employee Rights'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Rajesh Kumar',
    specialization: 'Civil Litigation',
    experience: '10 years',
    rating: 4.7,
    email: 'rajesh.kumar@example.com',
    phone: '555-098-7654',
    location: 'Chennai, Tamil Nadu',
    firm: 'Kumar Legal Advisors',
    education: 'University of Madras',
    practicingAreas: ['Civil Law', 'Family Disputes', 'Property Disputes'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'John Doe',
    specialization: 'Intellectual Property Law',
    experience: '10 years',
    rating: 4.5,
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    location: 'Delhi, Delhi',
    firm: 'Doe Law Firm',
    education: 'Harvard Law School',
    practicingAreas: ['Intellectual Property', 'Patent Law', 'Trademark Law'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Jane Smith',
    specialization: 'Corporate Law',
    experience: '8 years',
    rating: 4.7,
    email: 'jane.smith@example.com',
    phone: '987-654-3210',
    location: 'Mumbai, Maharashtra',
    firm: 'Smith & Associates',
    education: 'Stanford Law School',
    practicingAreas: ['Corporate Law', 'Mergers & Acquisitions', 'Business Law'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Michael Johnson',
    specialization: 'Criminal Defense',
    experience: '12 years',
    rating: 4.9,
    email: 'michael.johnson@example.com',
    phone: '555-123-4567',
    location: 'Kolkata, West Bengal',
    firm: 'Johnson Criminal Defense',
    education: 'Yale Law School',
    practicingAreas: ['Criminal Defense', 'DUI', 'Drug Offenses'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Emily Davis',
    specialization: 'Family Law',
    experience: '6 years',
    rating: 4.2,
    email: 'emily.davis@example.com',
    phone: '555-234-5678',
    location: 'Bengaluru, Karnataka',
    firm: 'Davis Family Law',
    education: 'University of Miami School of Law',
    practicingAreas: ['Divorce', 'Child Custody', 'Spousal Support'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'David Lee',
    specialization: 'Real Estate Law',
    experience: '15 years',
    rating: 4.3,
    email: 'david.lee@example.com',
    phone: '555-345-6789',
    location: 'Hyderabad, Telangana',
    firm: 'Lee Real Estate Law',
    education: 'University of Texas Law School',
    practicingAreas: ['Real Estate Law', 'Property Disputes', 'Landlord-Tenant'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Laura Green',
    specialization: 'Immigration Law',
    experience: '5 years',
    rating: 4.4,
    email: 'laura.green@example.com',
    phone: '555-456-7890',
    location: 'Chennai, Tamil Nadu',
    firm: 'Green Immigration Law',
    education: 'UC Berkeley School of Law',
    practicingAreas: ['Immigration Law', 'Visas', 'Green Cards'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Robert White',
    specialization: 'Employment Law',
    experience: '9 years',
    rating: 4.6,
    email: 'robert.white@example.com',
    phone: '555-567-8901',
    location: 'Pune, Maharashtra',
    firm: 'White Employment Law',
    education: 'Columbia Law School',
    practicingAreas: ['Employment Law', 'Labor Disputes', 'Workplace Discrimination'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Sophia Black',
    specialization: 'Personal Injury Law',
    experience: '7 years',
    rating: 4.8,
    email: 'sophia.black@example.com',
    phone: '555-678-9012',
    location: 'Ahmedabad, Gujarat',
    firm: 'Black Injury Law',
    education: 'University of Denver Sturm College of Law',
    practicingAreas: ['Personal Injury', 'Accident Law', 'Medical Malpractice'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'James Harris',
    specialization: 'Tax Law',
    experience: '20 years',
    rating: 5.0,
    email: 'james.harris@example.com',
    phone: '555-789-0123',
    location: 'Lucknow, Uttar Pradesh',
    firm: 'Harris Tax Advisors',
    education: 'Georgetown University Law Center',
    practicingAreas: ['Tax Law', 'Tax Planning', 'Corporate Tax'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  },
  {
    name: 'Olivia Martinez',
    specialization: 'Environmental Law',
    experience: '11 years',
    rating: 4.5,
    email: 'olivia.martinez@example.com',
    phone: '555-890-1234',
    location: 'Bhopal, Madhya Pradesh',
    firm: 'Martinez Environmental Law',
    education: 'University of Oregon School of Law',
    practicingAreas: ['Environmental Law', 'Water Law', 'Wildlife Law'],
    imageUrl: 'https://i.pinimg.com/564x/29/55/59/295559e87b67fde4bbd5d5049d67e678.jpg',
  }
];

export default lawyersData;
