const lawyersData = [
  {
    name: 'John Doe',
    specialization: 'Intellectual Property Law',
    experience: '10 years',
    rating: 4.5,
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    location: 'New York, NY',
    firm: 'Doe Law Firm',
    education: 'Harvard Law School',
    practicingAreas: ['Intellectual Property', 'Patent Law', 'Trademark Law'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'Jane Smith',
    specialization: 'Corporate Law',
    experience: '8 years',
    rating: 4.7,
    email: 'jane.smith@example.com',
    phone: '987-654-3210',
    location: 'Los Angeles, CA',
    firm: 'Smith & Associates',
    education: 'Stanford Law School',
    practicingAreas: ['Corporate Law', 'Mergers & Acquisitions', 'Business Law'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'Michael Johnson',
    specialization: 'Criminal Defense',
    experience: '12 years',
    rating: 4.9,
    email: 'michael.johnson@example.com',
    phone: '555-123-4567',
    location: 'Chicago, IL',
    firm: 'Johnson Criminal Defense',
    education: 'Yale Law School',
    practicingAreas: ['Criminal Defense', 'DUI', 'Drug Offenses'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'Emily Davis',
    specialization: 'Family Law',
    experience: '6 years',
    rating: 4.2,
    email: 'emily.davis@example.com',
    phone: '555-234-5678',
    location: 'Miami, FL',
    firm: 'Davis Family Law',
    education: 'University of Miami School of Law',
    practicingAreas: ['Divorce', 'Child Custody', 'Spousal Support'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'David Lee',
    specialization: 'Real Estate Law',
    experience: '15 years',
    rating: 4.3,
    email: 'david.lee@example.com',
    phone: '555-345-6789',
    location: 'Austin, TX',
    firm: 'Lee Real Estate Law',
    education: 'University of Texas Law School',
    practicingAreas: ['Real Estate Law', 'Property Disputes', 'Landlord-Tenant'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'Laura Green',
    specialization: 'Immigration Law',
    experience: '5 years',
    rating: 4.4,
    email: 'laura.green@example.com',
    phone: '555-456-7890',
    location: 'San Francisco, CA',
    firm: 'Green Immigration Law',
    education: 'UC Berkeley School of Law',
    practicingAreas: ['Immigration Law', 'Visas', 'Green Cards'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'Robert White',
    specialization: 'Employment Law',
    experience: '9 years',
    rating: 4.6,
    email: 'robert.white@example.com',
    phone: '555-567-8901',
    location: 'Seattle, WA',
    firm: 'White Employment Law',
    education: 'Columbia Law School',
    practicingAreas: ['Employment Law', 'Labor Disputes', 'Workplace Discrimination'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'Sophia Black',
    specialization: 'Personal Injury Law',
    experience: '7 years',
    rating: 4.8,
    email: 'sophia.black@example.com',
    phone: '555-678-9012',
    location: 'Denver, CO',
    firm: 'Black Injury Law',
    education: 'University of Denver Sturm College of Law',
    practicingAreas: ['Personal Injury', 'Accident Law', 'Medical Malpractice'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'James Harris',
    specialization: 'Tax Law',
    experience: '20 years',
    rating: 5.0,
    email: 'james.harris@example.com',
    phone: '555-789-0123',
    location: 'Washington, DC',
    firm: 'Harris Tax Advisors',
    education: 'Georgetown University Law Center',
    practicingAreas: ['Tax Law', 'Tax Planning', 'Corporate Tax'],
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    name: 'Olivia Martinez',
    specialization: 'Environmental Law',
    experience: '11 years',
    rating: 4.5,
    email: 'olivia.martinez@example.com',
    phone: '555-890-1234',
    location: 'Portland, OR',
    firm: 'Martinez Environmental Law',
    education: 'University of Oregon School of Law',
    practicingAreas: ['Environmental Law', 'Water Law', 'Wildlife Law'],
    imageUrl: 'https://via.placeholder.com/150',
  }
];

export default lawyersData;
